version: '3.7'
services:
  app:
    build: .
    ports:
      - '4000:4000'
    depends_on:
      - postgres
  postgres:
    image: postgres:13
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: unifood
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: